version: "3.9"
services:
  db:
    container_name: db
    restart: always
    build: ./db
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  app:
    container_name: app
    build: app
    volumes:
      - ./app/:/go/src/github.com/mr-yoyo/anti_bruteforce/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["/project/app", "http-server", "-c", "/project/config.yml"]