http:
  port: 8080

db:
  dataSource:
    - "postgres://user:password@db:5432/db?sslmode=disable&binary_parameters=yes"
  driver: postgres
  maxOpenConns: 30
  maxIdleConns: 30
  connMaxLifetime: 1h

policy: # per minute
  same_login: 10
  same_password: 100
  same_ip: 1000

